#!/usr/bin/env python

from setuptools import setup

setup(name='algorismi',
      version='0.0.1',
      description='my collection of algorithm implementations',
      author='Tianyu Zhao',
      author_email='davidxk@outlook.com',
      url='https://github.com/davidxk/Algorithm-Implementations',
      packages=[
          "algorismi.binary_indexed_tree", "algorismi.binary_search",
          "algorismi.bst", "algorismi.disjoint_set", "algorismi.dp",
          "algorismi.dutch_national_flag", "algorismi.graph",
          "algorismi.hashset", "algorismi.heap", "algorismi.linked_list",
          "algorismi.majority_vote", "algorismi.math", "algorismi.mst",
          "algorismi.recursion", "algorismi.sampling",
          "algorismi.segment_tree", "algorismi.selection",
          "algorismi.shortest_path", "algorismi.shuffle", "algorismi.sorting", 
          "algorismi.stack", "algorismi.string", "algorismi.topo_sort",
          "algorismi.traverse_tree", "algorismi.trie",
          ],
      package_dir={
          "algorismi.binary_indexed_tree": "binary_indexed_tree/py3",
          "algorismi.binary_search": "binary_search/py3",
          "algorismi.bst": "bst/py3",
          "algorismi.disjoint_set": "disjoint_set/py3",
          "algorismi.dp": "dp/py3",
          "algorismi.dutch_national_flag": "dutch_national_flag/py3",
          "algorismi.graph": "graph/py3",
          "algorismi.hashset": "hashset/py3",
          "algorismi.heap": "heap/py3",
          "algorismi.linked_list": "linked_list/py3",
          "algorismi.majority_vote": "majority_vote/py3",
          "algorismi.math": "math/py3",
          "algorismi.mst": "mst/py3",
          "algorismi.recursion": "recursion/py3",
          "algorismi.sampling": "sampling/py3",
          "algorismi.segment_tree": "segment_tree/py3",
          "algorismi.selection": "selection/py3",
          "algorismi.shortest_path": "shortest_path/py3",
          "algorismi.shuffle": "shuffle/py3",
          "algorismi.sorting": "sorting/py3",
          "algorismi.stack": "stack/py3",
          "algorismi.string": "string/py3",
          "algorismi.topo_sort": "topo_sort/py3",
          "algorismi.traverse_tree": "traverse_tree/py3",
          "algorismi.trie": "trie/py3",
          }
     )
